# Change these first
owner: Ein-Tim
repo: uptime-monitoring

sites:
  - name: Corona-Warn-App webiste
    url: https://www.coronawarn.app
#  - name: CWA Logupload
#    url: hhttps://logupload.coronawarn.app
  - name: CWA Main Server
    url: https://svc90.main.px.t-online.de/
  - name: CWA RAT portal
    url: https://schnelltestportal.de
  - name: CWA RAT map
    url: https://map.schnelltestportal.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
